# Generated by Django 5.1.5 on 2025-01-19 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_teacherprofile_created_at_teacherprofile_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.TextField(blank=True, verbose_name='Интересы')),
                ('education_level', models.CharField(choices=[('school', 'Школьник'), ('bachelor', 'Бакалавр'), ('master', 'Магистр'), ('phd', 'PhD')], max_length=20, verbose_name='Уровень образования')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль студента',
                'verbose_name_plural': 'Профили студентов',
            },
        ),
    ]
