# Generated by Django 5.1.5 on 2025-01-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_promocode_updated_at_alter_promocode_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='currency',
            field=models.CharField(choices=[('KGS', 'Кыргызский сом'), ('USD', 'Доллар США'), ('RUB', 'Российский рубль')], default='KGS', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='course',
            name='excerpt',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('ky', 'Кыргызский'), ('en', 'Английский')], default='ru', max_length=2, verbose_name='Язык курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('review', 'На проверке'), ('published', 'Опубликован'), ('archived', 'В архиве')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
