# Generated by Django 5.1.5 on 2025-01-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_average_rating_course_favorites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta описание'),
        ),
        migrations.AddField(
            model_name='course',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta ключевые слова'),
        ),
        migrations.AddField(
            model_name='course',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta заголовок'),
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=2, max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
